### ISSUE TITLE
[frontend] Revisit web page design, color pallette, etc.

### ISSUE THREAD

**Issue by usachev63** [sharkov63/spbu-se-0-calculator#17]
Currently we have the design and color palette right from the frontend skeleton #3, copied from another source. We can create our own design and modify the style files.

**Comment by achvanov7** [comment]
I guess this little nitpick belongs here. I'd change **The History** to just **History** as the former sounds too formal

**Comment by virogg** [comment]
Changed the design. 
Waiting for feedback!
![image](https://github.com/user-attachments/assets/b8b60b43-3805-4365-8a37-c46ba8504f6f)

**Comment by usachev63** [comment]
@virogg It is very good, thank you. Please create PR

One nitpick: maybe we can consider `History` instead of `History:`
