### ISSUE TITLE
create components for calculator history

### ISSUE THREAD

**Issue by SibSurfer** [sharkov63/spbu-se-0-calculator#8]
1. you need to create React components with calculator history
2. you need to decide how often and when you should do calls to the api for the history of calculations

**Comment by usachev63** [comment]
PR #11 introduced very raw component for history, where the main addition is the code to fetch data from the server. So in this task we should enrich this component with the feature to _click_, which will set current value to the result of the history query. This is according to the requirement from Sprint0.pdf.

**Comment by usachev63** [comment]
Closed by [d64f7c3](https://github.com/sharkov63/spbu-se-0-calculator/commit/d64f7c3d12c9cc48da0052207da145d1b283e628)
